// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'confidenceBadge': string;
  'reconciledBadges': string;
}
export const cssExports: CssExports;
export default cssExports;
